[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
address = "0.0.0.0"
port = 1420
open = false
ws_protocol = "ws"

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "cp ./target/stylers/main.css $TRUNK_STAGING_DIR/"]